### ISSUE TITLE
Hashids can't be imported when using typescript

### ISSUE THREAD

**Issue by vagol942** [niieani/hashids.js#171]
When using typescript, the typescript compiler will throw the following error.

Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.  TS2569

    46 | 
    47 |     if (
  > 48 |       [...this.seps].length === 0 ||
       |           ^
    49 |       [...this.alphabet].length / [...this.seps].length > sepDiv
    50 |     ) {
    51 |       sepsLength = Math.ceil([...this.alphabet].length / sepDiv)

Tested with hashids ver 2.1.0 and typescript 3.7.2

**Comment by IceCreamYou** [comment]
I have the same problem - it's because we have different tsconfig settings than Hashids wants. With an ES5 target, if you don't enable `downlevelIteration` in tsconfig, strings are not spreadable. This repo targets esnext.

I am working around this with anonymous imports, e.g. `const Hashids = require('path/to/hashids')`, but `require` has a return type of `any` so this means I don't get type information. I'm okay with this for now because I have my own wrapper around Hashids but it's certainly not ideal.

**Comment by niieani** [comment]
I got rid of string spread, can you try the latest version? Thanks!

**Comment by IceCreamYou** [comment]
Confirmed fixed. Thanks!
