### ISSUE TITLE
Generated hashid size

### ISSUE THREAD

**Issue by PedroCoimbra** [niieani/hashids.js#366]
Today I am generating the hashid as follows:

```
const Hashids = require('hashids');

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

let number = 1419856
let hash = new Hashids('Salto do Pedro', 6, ALPHABET).encode(number)
console.log("Hash:", hash, ". Number:", number, ". Size:", hash.length)
```

So what is printed on the console is:
```
[Running] node "c:\Users\pedro\Desktop\teste\testPedro.js"
Hash: YMMMMM . Number: 1419856 . Size: 6

[Done] exited with code=0 in 0.258 seconds
```

However, if I change the variable 'number' to number 1419857 the result is:
```
[Running] node "c:\Users\pedro\Desktop\teste\testPedro.js"
Hash: DRVVVVV . Number: 1419857 . Size: 7

[Done] exited with code=0 in 0.245 seconds
```

My doubt is:
The alphabet I am going through has 26 characters and I defined that the minimum size of the hashid would be 6 characters, the maximum hashid that I would have available with 6 characters would not be 308.915.776 (26 * 26 * 26 * 26 * 26 * 26 )?
Why in the number 1.419.857 he already increased one more character in my hashid?

**Comment by niieani** [comment]
Hi @PedroCoimbra, to answer your why you need to look under the hood of the source code that generates the hashes. hashids do not have any guarantees on length. One of the reasons why this might be the case is because of the `seps` parameter that is `'cfhistuCFHISTU'` by default. 
It favors longer hashes that do not have characters specified in `seps` next to one another, which prevents English curses from showing up in the generated hash.

Compression is not a goal of this project.
