### ISSUE TITLE
Use BitInt instead of parseInt for number parser

### ISSUE THREAD

**Issue by lichenhao** [niieani/hashids.js#67]
As wish, using package [BigInt](https://www.npmjs.com/package/big-integer) instead of parseInt can accept larger than max value of JS number .

**Comment by miquelfire** [comment]
Already in the works with Pull Request #65

**Comment by niieani** [comment]
As @miquelfire mentioned, BigInt is supported natively in the prerelease of 2.0, if you want to help test, please install with: `yarn add hashids@next`.

If you need to use on an older environment, you can submit a PR against the `next` branch that allows one to provide a custom BigInt implementation via the constructor. Though, I'd prefer to keep it native-only, since most modern engines support it nowadays.
